name: R-publish
on: 
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  check-secret:
    runs-on: ubuntu-latest
    outputs:
      defined: ${{ steps.my-key.outputs.defined }}
    steps:
    - id: defined
      if: "${{ env.MY_KEY != '' }}"
      run: echo "::set-output name=defined::true"
      env:
        MY_KEY: ${{ secrets.token }}