name: R-publish
on: 
  workflow_call:
    secrets:
      secret:
        required: true

jobs:
  check-secret:
    runs-on: ubuntu-latest
    outputs:
      defined: ${{ steps.test.outputs.defined }}
    steps:
    - id: test
      if: "${{ env.MY_KEY != '' }}"
      run: echo "::set-output name=defined::true"
      env:
        MY_KEY: ${{ secrets.token }}