name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14.x', '16.x', '18.x']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm run test --ci --coverage --maxWorkers=2

      - name: Build
        run: pnpm build