name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.commit.outputs.commit_sha }}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: true

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm run test --ci --coverage --maxWorkers=2

      - name: Build
        run: pnpm build

        
  check-secret:
    name: Check NPM_TOKEN
    uses: ./.github/workflows/check-secret.yml
    secrets: 
      secret: ${{ secrets.NPM_TOKEN }}

  publish:
    name: Publish
    needs: [check-secret, build]
    if: needs.check-secret.outputs.defined == 'true'
    uses: ./.github/workflows/publish.yml
    secrets: 
      token: ${{ secrets.NPM_TOKEN }}

  clean:
    runs-on: ubuntu-latest
    needs: 
      - build 
      - check-secret
      - publish
      
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3
       
      - name: Some
        run: echo "TODO => Cleaning up"
