name: CI

on: 
  push:
    branches-ignore:
      - master
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm run test --ci --coverage --maxWorkers=2   


  # clean:
  #   runs-on: ubuntu-latest
  #   needs: test 

  #   steps:
  #     - name: Some
  #       run: echo "TODO => Cleaning up"
