name: CI

on: 
  push:
    branches-ignore:
      - master
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: true

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm run test --ci --coverage --maxWorkers=2   


  # clean:
  #   runs-on: ubuntu-latest
  #   needs: test 

  #   steps:
  #     - name: Some
  #       run: echo "TODO => Cleaning up"
