name: Publish
on: 
  workflow_run:
    workflows: [CI]
    types: 
      - completed
    branches: [main, master, dev]
    

jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' && secrets.NPM_TOKEN }}
    uses: ./.github/workflows/r-publish.yml
    secrets: inherit
     

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'  