name: Publish
on: 
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
     
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.token }}
          greater-version-only: true

      - name: TODO => Notification
        run: echo 'TODO => Build a Notification pipeline'
        