name: Publish
on: 
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  publish:
    name: Publish
    uses: JS-DevTools/npm-publish@v1
    with:
      token: ${{ secrets.token }}
      greater-version-only: true