name: Publish
on: 
  pull_request:
    branches:
      - master
      - main

jobs:

  publish:
    name: Publish
    runs-on: ubuntu-latest
     
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          greater-version-only: true
          dry-run: true

      # - name: TODO => Notification
      #   run: echo 'TODO => Build a Notification pipeline'
  
  # clean:
  #   runs-on: ubuntu-latest
  #   needs: publish
      
  #   steps:
       
  #     - name: Some
  #       run: echo "TODO => Cleaning up"
        